### ISSUE TITLE
Application launching error

### ISSUE THREAD

**Issue by bsarin** [Varian-MedicalAffairsAppliedSolutions/MAAS-PlanScoreCard#7]
![Script_error](https://user-images.githubusercontent.com/8137643/229439533-dafbd918-1510-4b70-85f5-391229fbebd2.JPG)

**Comment by mattcschmidt** [comment]
Hi bsarin,

The current version of the Plan Scorecard tool should be downloadable from this repository. Its expiration date has been moved to 01/01/2024. 
Thank you,
